import MiniCooperRed from '../../assests/images/MiniCooperRed.png';
export const carData = [
    {
        index: '1',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '2',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '3',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '4',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '5',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '6',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '7',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '8',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '9',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '10',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '11',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '12',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
    {
        index: '13',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'

    },
    {
        index: '14',
        brand: 'Mini Cooper',
        name: 'Mini Cooper',
        desc: 'dgfueofjhre irhgirho reg ir uier iriiruighg ruhosj z;kdpwi iiewy j8eosriq3wi ruejrieok W we',
        image: MiniCooperRed,
        kms:'300km',
        price: 'Rs. 5000000',
        status: 'In Stock',
        bodyStyle: 'Sedan',
        mileage: '35000km',
        transmission: '6-Speed Auto',
        engine:'DOHC 24-value-v6',
        color: 'Black',
        specs: '2-passenger, 2-door',
        condition:'Used',
        registration: 'Registered 2020',
        fuel: 'petrol',
        type: 'automatic'
    },
]